### ISSUE TITLE
Implement the ability to unfollow and follow a user

### ISSUE THREAD

**Issue by husseinm** [gunnertech/thumbwar-ios-client#112]
Tie the followers/following and the follow button of a users profile to the api so the data is actually retained server side.

**Comment by jiakeliu** [comment]
@CodySwannGT says this is already implemented? Feel free to assign to Mahdi if so.

**Comment by husseinm** [comment]
Should be corrected in the latest commit

**Comment by jiakeliu** [comment]
As noted in your email, @husseinm, the following/follower counts are still not functioning correctly.

**Comment by husseinm** [comment]
Should now be 100% - the update was pushed to TF

**Comment by jiakeliu** [comment]
Minor thing - can we remove that loading animation on Follower/Following and the Follow button?

**Comment by jiakeliu** [comment]
Why is the count loading so slowly? Is it because of Heroku? Count retrieval should be trivial right?

**Comment by husseinm** [comment]
Sure, I feel though that it may be a tad bit confusing for the user to 
have the buttons and text just simply pop out like that, but not at all 
difficult.

On 6/16/2015 4:27 PM, Jiake Liu wrote:
>
> Minor thing - can we remove that loading animation on 
> Follower/Following and the Follow button?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gunnertech/thumbwar-ios-client/issues/112#issuecomment-112559009>.
>

-- 
Mahdi Hussein
m@hdihusse.in <mailto:m@hdihusse.in> | mahdihusse.in

**Comment by jiakeliu** [comment]
Should not be a problem if they show up quickly. Just making sure it's not an algorithm problem but just a matter of upgrading hosting.

**Comment by husseinm** [comment]
Not necessarily, it is not a Heroku issue as by the time you are at the 
profile page the dyno has spun up and you are communicating with the 
server. The issue is that the count is actually getting all the 
followers/following user profiles individually and tallying them up, 
then displaying that tally.

On 6/16/2015 4:30 PM, Jiake Liu wrote:
>
> Why is the count loading so slowly? Is it because of Heroku? Count 
> retrieval should be trivial right?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gunnertech/thumbwar-ios-client/issues/112#issuecomment-112559769>.
>

-- 
Mahdi Hussein
m@hdihusse.in <mailto:m@hdihusse.in> | mahdihusse.in

**Comment by jiakeliu** [comment]
Hmm..Okay. I'm going to close this ticket and add to the list of performance improvements to be made in the future.
