### ISSUE TITLE
When I open the app from a cold start, the "Home" tab loads and the avatars for the first thumbwar load, but the avatars for the second thumbwars don't load until I scroll

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#13]

**Comment by CodySwannGT** [comment]
It says like this until you scroll:

![img_4761](https://cloud.githubusercontent.com/assets/292923/5995182/70028338-aa5a-11e4-844a-625db1b6e962.PNG)

**Comment by adamespn** [comment]
fix pushed

**Comment by CodySwannGT** [comment]
This is still happening. The image loads but the challenger avatar never does. 

![img_4783](https://cloud.githubusercontent.com/assets/292923/6033586/8c650eec-abe5-11e4-8a1f-eb28396daf1f.PNG)

**Comment by adamespn** [comment]
That description does not sound the same as the original bug report. Open a new bug, maybe?

**Comment by CodySwannGT** [comment]
It's exactly the same.

This is the original description: When I open the app from a cold start,
the "Home" tab loads and the avatars for the first thumbwar load, but the
avatars for the second thumbwars don't load until I scroll.

That is still exactly what's happening. The first thumbwar - both avatar
images load - the second thumbwar - only one avatar image loads until I
scroll.

On Tue, Feb 3, 2015 at 8:48 PM, adamespn <notifications@github.com> wrote:

> That description does not sound the same as the original bug report. Open
> a new bug, maybe?
>
> > On Feb 3, 2015, at 8:45 PM, Cody Swann <notifications@github.com> wrote:
> >
> > This is still happening. The image loads but the challenger avatar never
> does.
>
> >
> >
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/13#issuecomment-72775300>
> .
>



-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by adamespn** [comment]
"The image loads but the challenger avatar 'never'
> does."

Versus

> the "Home" tab loads and the avatars for the first thumbwar load, but the
> avatars for the second thumbwars don't load 'until I scroll.'

**Comment by CodySwannGT** [comment]
To clarify - I meant "the background image loads but the avatar image never
does"

I was just adding info that the background image loads but that the avatar
image still does not load.

On Tuesday, February 3, 2015, adamespn <notifications@github.com> wrote:

> "The image loads but the challenger avatar 'never'
> > does."
>
> Versus
>
> > the "Home" tab loads and the avatars for the first thumbwar load, but the
> > avatars for the second thumbwars don't load 'until I scroll.'
>
>
>
> > On Feb 3, 2015, at 8:50 PM, Cody Swann <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > It's exactly the same.
> >
> > This is the original description: When I open the app from a cold start,
> > the "Home" tab loads and the avatars for the first thumbwar load, but the
> > avatars for the second thumbwars don't load until I scroll.
> >
> > That is still exactly what's happening. The first thumbwar - both avatar
> > images load - the second thumbwar - only one avatar image loads until I
> > scroll.
> >
> > On Tue, Feb 3, 2015 at 8:48 PM, adamespn <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > That description does not sound the same as the original bug report.
> Open
> > > a new bug, maybe?
> > >
> > > > On Feb 3, 2015, at 8:45 PM, Cody Swann <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > >
> > > > This is still happening. The image loads but the challenger avatar
> never
> > > does.
> > >
> > > >
> > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/gunnertech/thumbwar-ios-client/issues/13#issuecomment-72775300
> >
> > > .
> > >
> >
> >
> >
> > --
> > Cody Swann - CEO, Gunner Technology
> > T: 213.915.4083 | cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');> | www.gunnertech.com
> > <http://www.gunnertech.com/>Skype: cody.swann
> >
> > *CONFIDENTIALITY NOTICE: This email message, together with any documents,
> > files and/or email messages attached to it, is intended for the sole use
> of
> > the individual or entity to whom it is addressed, and may contain
> > information that is legally privileged, confidential and restricted from
> > disclosure. If you are not the intended recipient, or responsible for
> > delivery to that person, you are hereby notified that any dissemination
> or
> > copying of this communication is STRICTLY PROHIBITED. In such case please
> > notify the sender by reply email and delete this message without reading,
> > printing or saving.*
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/13#issuecomment-72775762>
> .
>


-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by adamespn** [comment]
OK. Is this statement correct?

The original bug report was not a complaint that thumbwars that are not yet visible do not preload images.

The original bug report refers to a war that is at least partially visible.

In this case the (partially) visible war appears to be loading images - then does, in fact load one or more images - but does not load all visible images until the user scrolls.

**Comment by CodySwannGT** [comment]
Correct. The ThumbWars in the screen captures that are seen trying to load
the avatar images are the second ThumbWars in the list.

The screen cap is taken after loading the app with absolutely no
interaction.

On Tuesday, February 3, 2015, adamespn <notifications@github.com> wrote:

> OK. Is this statement correct?
>
> The original bug report was not a complaint that thumbwars that are not
> yet visible do not preload images.
>
> The original bug report refers to a war that is at least partially visible.
>
> In this case the (partially) visible war appears to be loading images -
> then does, in fact load one or more images - but does not load all visible
> images until the user scrolls.
>
>
> > On Feb 3, 2015, at 8:55 PM, Cody Swann <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > To clarify - I meant "the background image loads but the avatar image
> never
> > does"
> >
> > I was just adding info that the background image loads but that the
> avatar
> > image still does not load.
> >
> > On Tuesday, February 3, 2015, adamespn <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > "The image loads but the challenger avatar 'never'
> > > > does."
> > >
> > > Versus
> > >
> > > > the "Home" tab loads and the avatars for the first thumbwar load,
> but the
> > > > avatars for the second thumbwars don't load 'until I scroll.'
> > >
> > >
> > >
> > > > On Feb 3, 2015, at 8:50 PM, Cody Swann <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > >
> > > > It's exactly the same.
> > > >
> > > > This is the original description: When I open the app from a cold
> start,
> > > > the "Home" tab loads and the avatars for the first thumbwar load,
> but the
> > > > avatars for the second thumbwars don't load until I scroll.
> > > >
> > > > That is still exactly what's happening. The first thumbwar - both
> avatar
> > > > images load - the second thumbwar - only one avatar image loads
> until I
> > > > scroll.
> > > >
> > > > On Tue, Feb 3, 2015 at 8:48 PM, adamespn <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > >
> > > > > That description does not sound the same as the original bug
> report.
> > > Open
> > > > > a new bug, maybe?
> > > > >
> > > > > > On Feb 3, 2015, at 8:45 PM, Cody Swann <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > > > >
> > > > > > This is still happening. The image loads but the challenger
> avatar
> > > never
> > > > > does.
> > > > >
> > > > > >
> > > > > >
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/gunnertech/thumbwar-ios-client/issues/13#issuecomment-72775300
> > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Cody Swann - CEO, Gunner Technology
> > > > T: 213.915.4083 | cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');>
> > > <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');>');> |
> www.gunnertech.com
> > > > <http://www.gunnertech.com/>Skype: cody.swann
> > > >
> > > > *CONFIDENTIALITY NOTICE: This email message, together with any
> documents,
> > > > files and/or email messages attached to it, is intended for the sole
> use
> > > of
> > > > the individual or entity to whom it is addressed, and may contain
> > > > information that is legally privileged, confidential and restricted
> from
> > > > disclosure. If you are not the intended recipient, or responsible for
> > > > delivery to that person, you are hereby notified that any
> dissemination
> > > or
> > > > copying of this communication is STRICTLY PROHIBITED. In such case
> please
> > > > notify the sender by reply email and delete this message without
> reading,
> > > > printing or saving.*
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/gunnertech/thumbwar-ios-client/issues/13#issuecomment-72775762
> >
> > > .
> > >
> >
> >
> > --
> > Cody Swann - CEO, Gunner Technology
> > T: 213.915.4083 | cody@gunnertech.com
> <javascript:_e(%7B%7D,'cvml','cody@gunnertech.com');> | www.gunnertech.com
> > <http://www.gunnertech.com/>Skype: cody.swann
> >
> > *CONFIDENTIALITY NOTICE: This email message, together with any documents,
> > files and/or email messages attached to it, is intended for the sole use
> of
> > the individual or entity to whom it is addressed, and may contain
> > information that is legally privileged, confidential and restricted from
> > disclosure. If you are not the intended recipient, or responsible for
> > delivery to that person, you are hereby notified that any dissemination
> or
> > copying of this communication is STRICTLY PROHIBITED. In such case please
> > notify the sender by reply email and delete this message without reading,
> > printing or saving.*
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-ios-client/issues/13#issuecomment-72780252>
> .
>


-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by adamespn** [comment]
Still doing an RCA on this. I can't tell if this is a "repaint" problem or if there is a race condition.
Multiple threads are taking action within milliseconds from each other, so it's hard to pin down.

**Comment by adamespn** [comment]
I found the issue - now searching for the fix

**Comment by adamespn** [comment]
fixed
